{include file="$template/includes/alert.tpl" type="info" msg=$message}

{if $error}
  {include file="$template/includes/alert.tpl" type="error" msg=$error}
{/if}

{if $successful}
  {include file="$template/includes/alert.tpl" type="success" msg=$LANG.changessavedsuccessfully textcenter=true}
{/if}

<form class="form-horizontal" method="post" action="{$smarty.server.PHP_SELF}?id={$domainid}&action=add">
  <input type="hidden" name="sub" value="save" />
  <input type="hidden" name="domainid" value="{$domainid}" />

  <table class="table table-striped">
    <thead>
      <tr>
        <th>KeyTag <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="An integer in the range 0 to 65535 that is used to identify the DNSSEC record."></span></th>
        <th>Algorithm <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="The algorithm used to generate the signature."></span></th>
        <th>DigestType <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="The algorithm type that was used to construct the digest."></span></td></th>
        <th>Digest <span class="glyphicon glyphicon-info-sign" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="A string value generated by the algorithm."></span></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {foreach from=$dnssec item=sec}
        <tr>
          <td>{$sec.keyTag}</td>
          <td>{$sec.alg}</td>
          <td>{$sec.digestType}
          <td>{$sec.digest}</td>
          <td>
          <a href="{$smarty.server.PHP_SELF}?id={$domainid}&amp;action=rem&amp;keytag={$sec.keyTag}&amp;alg={$sec.alg}&amp;digesttype={$sec.digestType}&amp;digest={$sec.digest}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">
            <span aria-hidden="true" class="glyphicon glyphicon-trash"></span>
          </a>
        </td>
        </tr>
      {/foreach}
      <tr>
        <td><input type="text" class="form-control" name="keyTag" maxlength="65535" placeholder="0 - 65535" required> </td>
        <td>
          <select name="alg" class="form-control" required>
            <option value="3">3</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="10">10</option>
            <option value="12">12</option>
            <option value="13">13</option>
            <option value="14">14</option>
          </select>
        </td>
        <td>
          <select name="digestType" class="form-control" required>
            <option value="1">1 (SHA-1)</option>
            <option value="2">2 (SHA-256)</option>
          </select>
        </td>
        <td>
          <textarea name="digest" class="form-control" rows="2" required></textarea>
        </td>
        <td><input type="submit" value="Add" class="btn btn-success" /></td>
      </tr>
    </tbody>
  </table>
</form>